- ansible.builtin.copy:
    dest: /etc/yum.repos.d/rabbitmq.repo
    src: rabbitmq.repo

  name: copy rabbitmq repo


- ansible.builtin.dnf:
    name: rabbitmq-server
    state: present
  name: install rabbitmq server


- ansible.builtin.service:
    enabled: yes
    name: rabbitmq-server
    state: restarted

  name: start and enable rabbitmq


- community.rabbitmq.rabbitmq_user:
    password: roboshop123
    permissions:
      - configure_priv: .*
        read_priv: .*
        vhost: /
        write_priv: .*

    state: present    
    user: roboshop 

  name: create rabbitmq user