- ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
  name: app setup
  tags:
    - deployment


- ansible.builtin.include_role:
    name: common
    tasks_from: nodejs-setup.yaml
  name: nodejs setup
  tags:
    - deployment


- ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml
  name: systemd setup


- ansible.builtin.copy:
    dest: /etc/yum.repos.d/mongo.repo
    src: mongo.repo

  name: copy mongo repo


- ansible.builtin.dnf:
    name: mongosh   # ✅ FIXED (was mongodb-mongosh ❌)
    state: present
  name: install mongodb client


- ansible.builtin.command: >
    mongosh --host {{ MONGODB_HOST }} --quiet
    --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  name: check products loaded
  register: catalogue_output


- ansible.builtin.shell: >
    mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  name: load the products
  when: catalogue_output.stdout | int < 0


- ansible.builtin.service:
    enabled: yes
    name: catalogue
    state: restarted

  name: start catalogue
  tags:
    - deployment