- ansible.builtin.user:
    comment: "Roboshop system user"
    home: /app
    name: roboshop
    shell: /sbin/nologin
    system: true

  name: create system user roboshop


- ansible.builtin.file:
    path: /app
    state: absent
  name: delete app directory


- ansible.builtin.file:
    path: /app
    state: directory
  name: create app directory


- ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent
  name: delete {{ component }} zip file


- ansible.builtin.get_url:
    dest: /tmp/{{ component }}.zip
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-{{ app_version }}.zip 

  name: download {{ component }}


- ansible.builtin.unarchive:
    dest: /app
    remote_src: yes
    src: /tmp/{{ component }}.zip

  name: unarchieve {{ component }}