---
# Purpose: Prepare the Java environment and build the application
- ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - maven
    - mysql
  name: install maven and mysql client

- ansible.builtin.command:
    chdir: /app
    cmd: mvn clean package

  name: Build application with maven



- ansible.builtin.command:
    chdir: /app
    cmd: mv target/shipping-1.0.jar shipping.jar

  name: Rename artifact for service