
---
# Purpose: Prepare the NodeJS environment for backend microservices
- ansible.builtin.command: dnf module enable nodejs:20 -y
  # We use dnf module to ensure we get the specific version required by the app
  name: enable nodejs 20


- ansible.builtin.dnf:
    name:
      - nodejs
      - npm
    state: present
  name: install nodejs npm


- community.general.npm:
    path: /app
  # community.general.npm is the standard module to handle package.json
  name: install dependencies