- ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - python3 
  - gcc 
  - python3-devel
  name: install python

- ansible.builtin.pip:
    executable: pip3.9
    requirements: requirements.txt

  args:
    chdir: /app
  name: install dependencie